<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260316135322 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "user_order" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_17EB68C0A76ED395 ON "user_order" (user_id)');
        $this->addSql('CREATE TABLE order_product_variant (order_id INT NOT NULL, product_variant_id INT NOT NULL, PRIMARY KEY (order_id, product_variant_id))');
        $this->addSql('CREATE INDEX IDX_EB9367418D9F6D38 ON order_product_variant (order_id)');
        $this->addSql('CREATE INDEX IDX_EB936741A80EF684 ON order_product_variant (product_variant_id)');
        $this->addSql('ALTER TABLE "user_order" ADD CONSTRAINT FK_17EB68C0A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE order_product_variant ADD CONSTRAINT FK_EB9367418D9F6D38 FOREIGN KEY (order_id) REFERENCES "user_order" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE order_product_variant ADD CONSTRAINT FK_EB936741A80EF684 FOREIGN KEY (product_variant_id) REFERENCES product_variant (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "user_order" DROP CONSTRAINT FK_17EB68C0A76ED395');
        $this->addSql('ALTER TABLE order_product_variant DROP CONSTRAINT FK_EB9367418D9F6D38');
        $this->addSql('ALTER TABLE order_product_variant DROP CONSTRAINT FK_EB936741A80EF684');
        $this->addSql('DROP TABLE "user_order"');
        $this->addSql('DROP TABLE order_product_variant');
    }
}
